---
title: "Analysis"
author: "Marlon Schumacher"
date: "26 8 2018"
output: pdf_document
---

#Loading Data
```{r}
load("/Users/marlonschumacher/Documents/2_Master/Git_Projekte/SEM_paper/allbus_imp.RData")
allbus_imp$siops08
```

#Bad Loadings
```{r}
allbus <- allbus %>%
  select(mc01, mc02, mc03, mc04, wghtpew)

mod_loadings <- '#measurement
Kontakt =~ 1*mc04 + mc03 + mc02 + mc01

#Error
mc01 ~~ mc01
mc02 ~~ mc02
mc03 ~~ mc03
mc04 ~~ mc04'

fit_loads <- cfa(model = mod_loadings,
                 data = allbus,
                 estimator = "MLM")

allbus_design <- svydesign(id = ~1,
                           weights = ~wghtpew,
                           data =allbus)

fit_loads_weight <- lavaan.survey(lavaan.fit = fit_loads,
                                  survey.design = allbus_design)

semPaths(fit_loads_weight,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10, # size latent
         sizeLat2 = 10, # height latent
         sizeMan = 6, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.85, # edding size of parameters
         curve = 3)

summary(fit_loads_weight, standardized = T, fit.measures = T)

```



#Messmodell
```{r}
library(lavaan)
library(semPlot)

# Neuer Datensatz
allbus_imp_vis <- allbus_imp %>% 
  select(-age, -sex, -work)

# Veränderung der Labels zwecks besserer Darstellung in der Arbeit
colnames(allbus_imp_vis) <- c("Soz.",  "Whg", "Arb.", "Straf",
                          "Halt", "Schul.", "Kont.", "Bild.", "Beruf",
                          "Äq.E.","Schicht", "gewicht")

# Spezifikation des Messmodells
mod_mes_vis <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.

#Disturbance
Abl. ~~ Abl.
SES ~~ SES

#Covariance
Abl. ~~ SES'

# Fitting des spezifizierten Messmodells
fit_mes <- cfa(model = mod_mes_vis,
               estimator = "MLM",
               data = allbus_imp_vis) 

library("lavaan.survey")
alb_sd_vis <- survey::svydesign(id= ~1,
                  weights= ~gewicht,
                  data= allbus_imp_vis)

surveyfit_mes <- lavaan.survey(lavaan.fit = fit_mes,
                           survey.design = alb_sd_vis)

# Plot of weightet fit (Fit-Maße noch mit PowerPoint hinzufügen)
semPaths(surveyfit_mes,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10, # size latent
         sizeLat2 = 10, # height latent
         sizeMan = 6, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.85, # edding size of parameters
         curve = 3)

# Fitmaße und mehr
summary(surveyfit_mes, standardized = T, fit.measures = T)
fitmeasures(surveyfit_mes)

# Residuen noch überprüfen (in Anhang reicht)


# Modifikationsindizes für zwecks möglicher Optimierungen
modi_1 <- modificationindices(surveyfit_mes, sort. = TRUE)

# creating table (latex)
modi_df1 <- as.data.frame(modi_1)
modi_df1 <- modi_df1 %>% 
  select(-epc, -sepc.lv, -sepc.nox)

# latex code for the table -> in Latex anpassen
xtable(modi_df1)

# Obtaining std. Residuqls
get_std_cor <- function(fit) {
  N_cov <- list(
    observed = inspect(fit, 'sampstat')$cov ,
     fitted = fitted(fit)$cov )
N_cor <- list(
    observed = cov2cor(N_cov$observed),
    fitted = cov2cor(N_cov$fitted) )
N_cor$residual <- N_cor$observed - N_cor$fitted
lapply(N_cor, function(X) round(X, 2))
}

resid_mes <- get_std_cor(surveyfit_mes)
resid_mes.df <- resid_mes$residual

xtable(resid_mes.df)


```

#freie Schätzung MI - Messmodell 2 (Anhang)
```{r}
# Spezifikation mit Fehlerkorrelation
mod_mes_vis_o <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.

#Fehlerkor.
Bild. ~~ Beruf

#Disturbance
Abl. ~~ Abl.
SES ~~ SES

#Covariance
Abl. ~~ SES'

fit_mes_o <- cfa(model = mod_mes_vis_o,
               estimator = "MLM",
               data = allbus_imp_vis) 

surveyfit_mes_o <- lavaan.survey(lavaan.fit = fit_mes_o,
                           survey.design = alb_sd_vis)

semPaths(surveyfit_mes_o,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10, # size latent
         sizeLat2 = 10, # height latent
         sizeMan = 6, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.85, # edding size of parameters
         curve = 3)

summary(surveyfit_mes_o, standardized = T, fit.measures = T)
fitmeasures(surveyfit_mes_o)

# Modifikationsindizes
modi_2 <- modificationindices(surveyfit_mes_o, sort. = TRUE)

# creating table (latex)
modi_df2 <- as.data.frame(modi_2)
modi_df2 <- modi_df2 %>% 
  select(-epc, -sepc.lv, -sepc.nox)

# latex code for the table -> in Latex anpassen
xtable(modi_df2)

# skalierter Chi-quadrat differenzentest
anova(surveyfit_mes, surveyfit_mes_o)
```


#Strkturgleichungsmodell mit Pfaden
```{r}
# Spezifikation des Modells
mod_1_vis <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.
Kont. ~~ Kont.

#Disturbance
SES ~~ SES
Abl. ~~ Abl.

#Regression
Abl. ~ SES
Abl. ~ Kont.'

fit_mod1 <- cfa(model = mod_1_vis,
               estimator = "MLM",
               data = allbus_imp_vis) 

surveyfit_mod1 <- lavaan.survey(lavaan.fit = fit_mod1,
                           survey.design = alb_sd_vis)

semPaths(surveyfit_mod1,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 8, # size latent
         sizeLat2 = 8, # height latent
         sizeMan = 6, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.7, # edding size of parameters
         curve = 3,
         layout = "tree2",
         rotation = 2)

summary(surveyfit_mod1, standardized = T, fit.measures = T)

# getting unstandardized parameters
tab_mod1_est <- as.data.frame(parameterestimates(surveyfit_mod1))

tab_mod1_est <- tab_mod1_est %>% 
  select(-ci.lower, -ci.upper, -z)

#table for est
xtable(tab_mod1_est)

# standardisierte Parameter
tab_mod1_std <- as.data.frame(standardizedSolution(surveyfit_mod1))
tab_mod1_std <- tab_mod1_std %>% 
  select(-z, -ci.upper, -ci.lower)

#table for std -> combine in latex
xtable(tab_mod1_std)

# std. Residuals
resid_mod1 <- get_std_cor(surveyfit_mod1)
resid_mod1.df <- resid_mod1$residual

# Latex code for table
xtable(resid_mod1.df)

# Modifikationsindizes
modi_m1 <- modificationindices(surveyfit_mod1, sort. = TRUE)

# creating table (latex)
modi_m1.df <- as.data.frame(modi_m1)
modi_m1.df <- modi_m1.df %>% 
  select(-epc, -sepc.lv, -sepc.nox)

# latex code for the table -> in Latex anpassen
xtable(modi_m1.df)

```

# Strukturgleichungsmodell mit Pfaden & Covarianz zwischen SES - Kontakt (literatur noch zitieren!)
```{r}
# Spezifikation des Modells
mod_2_vis <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.
Kont. ~~ Kont.

#Co-Variance
SES ~~ Kont.

#Disturbance
SES ~~ SES
Abl. ~~ Abl.

#Regression
Abl. ~ SES
Abl. ~ Kont.'

fit_mod2 <- cfa(model = mod_2_vis,
                data = allbus_imp_vis,
                estimator = "MLM")

surveyfit_mod2 <- lavaan.survey(lavaan.fit = fit_mod2,
                           survey.design = alb_sd_vis)

semPaths(surveyfit_mod2,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 8, # size latent
         sizeLat2 = 8, # height latent
         sizeMan = 5, # size manifest
         sizeInt = 2.5, 
         edge.label.cex=0.7, # edding size of parameters
         curve = 3,
         layout = "tree2",
         rotation = 2)

summary(surveyfit_mod2, standardized = T, fit.measures = T)

# Signifikanter Differenzentest *yay*
anova(surveyfit_mod2, surveyfit_mod1)

sempaths

```



```{r}
mod_mes <- '#measurement model
Abl. =~ 1*mp06 + mp04 + mp02 + mp07 + mp09 + mp11
SES =~ 1*isced11 + siops08 + di08c + id02

#Error
mp02 ~~ mp02
mp04 ~~ mp04
mp06 ~~ mp06
mp07 ~~ mp07
mp09 ~~ mp09
mp11 ~~ mp11
isced11 ~~ isced11
id02 ~~ id02
siops08 ~~ siops08
di08c ~~ di08c

#Disturbance
Abl. ~~ Abl.
SES ~~ SES

#Covariance
Abl. ~~ SES'



fit_mes <- cfa(model = mod_mes,
               estimator = "MLM",
               data = allbus_imp) # KEEP GOING!

library("lavaan.survey")
alb_sd <- survey::svydesign(id= ~1,
                  weights= ~wghtpew,
                  data= allbus_imp)

surveyfit <- lavaan.survey(lavaan.fit = fit_mes,
                           survey.design = alb_sd)

semPaths(fit_mes,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10,
         sizeLat2 = 10,
         curve = 3)

semPaths(surveyfit,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10,
         sizeLat2 = 10,
         curve = 3,
         layout = "spring")
title("Modell 1: Ausländerablehnung auf sozioökonomischen Status", adj = 0)

summary(fit_mes, standardized = T, fit.measures = T)

modificationindices(fit_mes, sort. = TRUE)
```


#Model 1 - SES - Abl.
```{r, results='asis'}

mod1 <- '#measurement model
Abl. =~ 1*mp02 + mp04 + mp06 + mp07 + mp09 + mp11
SES =~ 1*isced11 + siops08 + di08c + id02

#Error
mp02 ~~ mp02
mp04 ~~ mp04
mp06 ~~ mp06
mp07 ~~ mp07
mp09 ~~ mp09
mp11 ~~ mp11
isced11 ~~ isced11
id02 ~~ id02
siops08 ~~ siops08
di08c ~~ di08c

#Disturbances
Abl. ~~ Abl.
SES ~~ SES

#Regression
Abl. ~ SES'

fit1 <- cfa(model = mod1, 
            data = allbus_oD,
            estimator = "MLM")

# install.packages("lavaan.survey")
library("lavaan.survey")
alb_sd <- survey::svydesign(id= ~1,
                  weights= ~wghtpew,
                  data= allbus_imp)

surveyfit <- lavaan.survey(lavaan.fit = fit1,
                           survey.design = alb_sd)

summary(surveyfit, standardized = T, fit.measures = T)

summary(fit1, standardized = T, fit.measures = T)

semPaths(fit1,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10,
         sizeLat2 = 10,
         curve = 3,
         layout = "spring")
title("Modell 1: Ausländerablehnung auf sozioökonomischen Status", adj = 0)

fitmeasures(fit1, "all")
summary(fit1, standardized = T, fit.measures = T)

pars.factors <- standardizedSolution(fit1)[ standardizedSolution(fit1)[,'op']=='=~', c(1:5)]
pars.regressions <- standardizedSolution(fit1)[ standardizedSolution(fit1)[,'op']=='~', c(1:5)]
rbind(pars.factors, pars.regressions)


library(xtable)
xtable(rbind(pars.factors, pars.regressions))

# xtable(modindices(fit1))
```


#Model 2: Abl. auf SES und Kontakt
```{r}
mod2 <- '#measurement model
Abl. =~ 1*mp02 + mp04 + mp06 + mp07 + mp09 + mp11
SES =~ 1*isced11 + siops08 + di08c + id02


#Error
mp02 ~~ mp02
mp04 ~~ mp04
mp06 ~~ mp06
mp07 ~~ mp07
mp09 ~~ mp09
mp11 ~~ mp11
mc04 ~~ mc04
isced11 ~~ isced11
di08c ~~ di08c
id02 ~~ id02

#Covariance
SES ~~ mc04

#Disturbances
Abl. ~~ Abl.
SES ~~ SES

#Regression
Abl. ~ SES
Abl. ~ mc04'

fit2 <- cfa(model = mod2, 
            data = allbus_imp,
            estimator = "MLM")

semPaths(fit2,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10,
         sizeLat2 = 10,
         curve = 3,
         layout = "tree")
title("Modell 2: Ausländerablehnung auf sozioökonomischen Status und Kontakt", adj = 0)

summary(fit2, standardized = T, fit.measures = T)

```

#TEST
```{r}
test <- '#measurement model
Abl. =~ 1*mp02 + mp04 + mp06 + mp07 + mp09 + mp11
SES =~ 1*isced11 + siops08 + di08c + id02
K =~ 1*mc01 + mc02 + mc03 + mc04

#Error
mp02 ~~ mp02
mp04 ~~ mp04
mp06 ~~ mp06
mp07 ~~ mp07
mp09 ~~ mp09
mp11 ~~ mp11
mc04 ~~ mc04
isced11 ~~ isced11
di08c ~~ di08c
id02 ~~ id02

#Covariance
SES ~~ mc04

#Disturbances
Abl. ~~ Abl.
SES ~~ SES

#Regression
Abl. ~ SES
Abl. ~ mc04'

fit_t <- cfa(model = test, 
            data = allbus,
            estimator = "MLM")

semPaths(fit_t,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10,
         sizeLat2 = 10,
         curve = 3,
         layout = "tree")
title("Modell 2: Ausländerablehnung auf sozioökonomischen Status und Kontakt", adj = 0)

summary(fit2, standardized = T, fit.measures = T)

test_2 <- '#measurement model
K =~ 1*mc01 + mc02 + mc03'

fit_t2 <- cfa(model = test_2, 
            data = allbus,
            estimator = "MLM")

semPaths(fit_t2,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10,
         sizeLat2 = 10,
         curve = 3,
         layout = "tree")
title("Modell 2: Ausländerablehnung auf sozioökonomischen Status und Kontakt", adj = 0)
```

