---
title: "Analysis"
author: "Marlon Schumacher"
date: "13 8 2018"
output: pdf_document
---

#Packages
```{r}
install.packages("haven")
install.packages("tidyverse")
install.packages("magrittr")
install.packages("mvnmle")
install.packages("mice")
install.packages("tidyr")
install.packages("dplyr")
install.packages("semPlot")
install.packages("lavaan")
install.packages("corrplot")
install.packages("naniar")
install.packages("ggplot2")
install.packages("ISLR")
install.packages("stargazer")
install.packages("BaylorEdPsych") 
install.packages("xtable")
install.packages("MVN")
install.packages("pastecs")
install.packages("lavaan.survey")

library(haven)
library(tidyverse)
library(magrittr)
library(mvnmle)
library(mice)
library(tidyr)
library(dplyr)
library(semPlot)
library(lavaan)
library(corrplot)
library(naniar) # Package for missing analysis
library(ggplot2)
library(ISLR)
library(stargazer)
library(BaylorEdPsych) 
library(xtable)
library(MVN)
library(pastecs)
library(lavaan.survey)
```


#Loading Data
```{r}
load("allbus_imp.RData")
```

#Bad Loadings - Messmodell für Kontakt
```{r}
# Inspektion der Loadings anhand des gefilterten Datensatzes -> nur für den Anhang
allbus <- read_spss("allbus2016.sav") %>% 
  select(mc01, mc02, mc03, mc04, wghtpew, work)

colnames(allbus) <- c("Familie", "Arbeit", "Nachbar.", "Freund.", "wghtpew", "work")

# Filterung derjenigen, die kein Berufsprestige haben
allbus <- allbus[!(allbus$work == 4),]
allbus <- allbus[!(allbus$work == 3),]
allbus <- allbus[!(is.na(allbus$wghtpew)),]

mod_loadings <- '#measurement
Kontakt =~ 1*Freund. + Nachbar. + Arbeit + Familie

#Error
Familie ~~ Familie
Arbeit ~~ Arbeit
Nachbar. ~~ Nachbar.
Freund. ~~ Freund.'

fit_loads <- cfa(model = mod_loadings,
                 data = allbus,
                 estimator = "MLM")

library("lavaan.survey")
allbus_design <- svydesign(id = ~1,
                           weights = ~wghtpew,
                           data =allbus)

fit_loads_weight <- lavaan.survey(lavaan.fit = fit_loads,
                                  survey.design = allbus_design)

semPaths(fit_loads_weight,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10, # size latent
         sizeLat2 = 10, # height latent
         sizeMan = 8, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.85, # edding size of parameters
         curve = 3)

summary(fit_loads_weight, standardized = T, fit.measures = T)

# Ohne Freund
mod_loadings2 <- '#measurement
Kontakt =~  1*Nachbar. + Arbeit + Familie

#Error
Familie ~~ Familie
Arbeit ~~ Arbeit
Nachbar. ~~ Nachbar.'

fit_loads2 <- cfa(model=mod_loadings2,
                  data=allbus,
                  estimator="MLM")

fit_loads2_w <- lavaan.survey(lavaan.fit = fit_loads2,
                              survey.design = allbus_design)

semPaths(fit_loads2_w,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10, # size latent
         sizeLat2 = 10, # height latent
         sizeMan = 8, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.85, # edding size of parameters
         curve = 3)
# Ebenso schlechte Loadings :(

```



#Messmodell
```{r}
library(lavaan)
library(semPlot)

# Neuer Datensatz
allbus_imp_vis <- allbus_imp %>% 
  select(-age, -sex, -work)

# Veränderung der Labels zwecks besserer Darstellung in der Arbeit
colnames(allbus_imp_vis) <- c("Soz.",  "Whg", "Arb.", "Straf",
                          "Halt", "Schul.", "Kont.", "Bild.", "Beruf",
                          "Äq.E.","Schicht", "gewicht")

# Spezifikation des Messmodells
mod_mes_vis <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.

#Disturbance
Abl. ~~ Abl.
SES ~~ SES

#Covariance
Abl. ~~ SES'

# Fitting des spezifizierten Messmodells
fit_mes <- cfa(model = mod_mes_vis,
               estimator = "MLM",
               data = allbus_imp_vis) 

alb_sd_vis <- survey::svydesign(id= ~1,
                  weights= ~gewicht,
                  data= allbus_imp_vis)

surveyfit_mes <- lavaan.survey(lavaan.fit = fit_mes,
                           survey.design = alb_sd_vis)

# Plot of weightet fit (Fit-Maße noch mit PowerPoint hinzufügen)
semPaths(surveyfit_mes,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10, # size latent
         sizeLat2 = 10, # height latent
         sizeMan = 6, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.85, # edding size of parameters
         curve = 3)

# Fitmaße und mehr // fitmeasures alle eig. schon in summary enthalten, aber zwecks Überprüfung
summary(surveyfit_mes, standardized = T, fit.measures = T)
fitmeasures(surveyfit_mes)

# Modifikationsindizes für zwecks möglicher Optimierungen -> die ersten 10 nehmen, sonst zu lang
modi_1 <- modificationindices(surveyfit_mes, sort. = TRUE)

# creating table (latex)
modi_df1 <- as.data.frame(modi_1)
modi_df1 <- modi_df1 %>% 
  select(-epc, -sepc.lv, -sepc.nox)

# latex code for the table -> in Latex anpassen
xtable(modi_df1)

# Obtaining std. Residuals -> in den Anhang und in der Arbeit Bezug drauf nehmen
get_std_cor <- function(fit) {
  N_cov <- list(
    observed = inspect(fit, 'sampstat')$cov ,
     fitted = fitted(fit)$cov )
N_cor <- list(
    observed = cov2cor(N_cov$observed),
    fitted = cov2cor(N_cov$fitted) )
N_cor$residual <- N_cor$observed - N_cor$fitted
lapply(N_cor, function(X) round(X, 2))
}

resid_mes <- get_std_cor(surveyfit_mes)
resid_mes.df <- resid_mes$residual

xtable(resid_mes.df)
```

#freie Schätzung MI - Messmodell 2 mit Fehlerkorrelation (kommt in den Anhang als Ergänzung)
```{r}
# Spezifikation mit Fehlerkorrelation
mod_mes_vis_o <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.

#Fehlerkor.
Bild. ~~ Beruf

#Disturbance
Abl. ~~ Abl.
SES ~~ SES

#Covariance
Abl. ~~ SES'

fit_mes_o <- cfa(model = mod_mes_vis_o,
               estimator = "MLM",
               data = allbus_imp_vis) 

surveyfit_mes_o <- lavaan.survey(lavaan.fit = fit_mes_o,
                           survey.design = alb_sd_vis)

semPaths(surveyfit_mes_o,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 10, # size latent
         sizeLat2 = 10, # height latent
         sizeMan = 6, # size manifest
         sizeInt = 3.5, 
         edge.label.cex=0.85, # edding size of parameters
         curve = 3)

summary(surveyfit_mes_o, standardized = T, fit.measures = T)
fitmeasures(surveyfit_mes_o)

# Modifikationsindizes
modi_2 <- modificationindices(surveyfit_mes_o, sort. = TRUE)

# creating table (latex)
modi_df2 <- as.data.frame(modi_2)
modi_df2 <- modi_df2 %>% 
  select(-epc, -sepc.lv, -sepc.nox)

# latex code for the table -> in Latex anpassen
xtable(modi_df2)

# skalierter Chi-quadrat differenzentest
anova(surveyfit_mes, surveyfit_mes_o)
```


#Strkturgleichungsmodell mit Pfaden - Modell 2 in HA
```{r}
# Spezifikation des Modells
mod_1_vis <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.
Kont. ~~ Kont.

#Disturbance
SES ~~ SES
Abl. ~~ Abl.

#Regression
Abl. ~ SES
Abl. ~ Kont.'

fit_mod1 <- cfa(model = mod_1_vis,
               estimator = "MLM",
               data = allbus_imp_vis) 

surveyfit_mod1 <- lavaan.survey(lavaan.fit = fit_mod1,
                           survey.design = alb_sd_vis)

semPaths(surveyfit_mod1,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 8, 
         sizeLat2 = 8, 
         sizeMan = 6, 
         sizeInt = 3.5, 
         edge.label.cex=0.7,
         curve = 3,
         layout = "tree2", # super layout in Kombination mit ritation = 2!
         rotation = 2)

summary(surveyfit_mod1, standardized = T, fit.measures = T)

# getting unstandardized parameters
tab_mod1_est <- as.data.frame(parameterestimates(surveyfit_mod1))

tab_mod1_est <- tab_mod1_est %>% 
  select(-ci.lower, -ci.upper, -z)

#table for est
xtable(tab_mod1_est)

# standardisierte Parameter
tab_mod1_std <- as.data.frame(standardizedSolution(surveyfit_mod1))
tab_mod1_std <- tab_mod1_std %>% 
  select(-z, -ci.upper, -ci.lower)

#table for std -> combine in latex
xtable(tab_mod1_std)

# std. Residuals -> ebenso in den Anhang
resid_mod1 <- get_std_cor(surveyfit_mod1)
resid_mod1.df <- resid_mod1$residual

# Latex code for table
xtable(resid_mod1.df)

# Modifikationsindizes; wieder die ersten 10 heranziehen
modi_m1 <- modificationindices(surveyfit_mod1, sort. = TRUE)

# creating table (latex)
modi_m1.df <- as.data.frame(modi_m1)
modi_m1.df <- modi_m1.df %>% 
  select(-epc, -sepc.lv, -sepc.nox)

# latex code for the table -> in Latex anpassen
xtable(modi_m1.df)

```

# Strukturgleichungsmodell mit Pfaden & Kovarianz zwischen SES & Kontakt - Modell 3 in HA
```{r}
# Spezifikation des Modells
mod_2_vis <- '#measurement model
Abl. =~ 1*Arb. + Whg + Soz. + Straf + Halt + Schul.
SES =~ 1*Bild. + Beruf + Äq.E. + Schicht

#Error
Soz. ~~ Soz.
Whg ~~ Whg
Arb. ~~ Arb.
Straf ~~ Straf
Halt ~~ Halt
Schul. ~~ Schul.
Bild. ~~ Bild.
Schicht ~~ Schicht
Beruf ~~ Beruf
Äq.E. ~~ Äq.E.
Kont. ~~ Kont.

#Co-Variance
SES ~~ Kont.

#Disturbance
SES ~~ SES
Abl. ~~ Abl.

#Regression
Abl. ~ SES
Abl. ~ Kont.'

fit_mod2 <- cfa(model = mod_2_vis,
                data = allbus_imp_vis,
                estimator = "MLM")

surveyfit_mod2 <- lavaan.survey(lavaan.fit = fit_mod2,
                           survey.design = alb_sd_vis)

semPaths(surveyfit_mod2,
         nCharNodes = 0,
         whatLabels = "std",
         sizeLat = 8, # size latent
         sizeLat2 = 8, # height latent
         sizeMan = 5, # size manifest
         sizeInt = 2.5, 
         edge.label.cex=0.7, # edding size of parameters
         curve = 3,
         layout = "tree2",
         rotation = 2)

summary(surveyfit_mod2, standardized = T, fit.measures = T)

# unstandardisierte Parameter
tab_mod2_est <- as.data.frame(parameterestimates(surveyfit_mod2))

# Entfernung nicht relevanter columns
tab_mod2_est <- tab_mod2_est %>% 
  select(-ci.lower, -ci.upper, -z)

#table for est
xtable(tab_mod2_est)

# standardisierte Parameter
tab_mod2_std <- as.data.frame(standardizedSolution(surveyfit_mod2))
tab_mod2_std <- tab_mod2_std %>% 
  select(-z, -ci.upper, -ci.lower)

#table for std -> combine in latex
xtable(tab_mod2_std)

# std. Residuals
resid_mod2 <- get_std_cor(surveyfit_mod2)
resid_mod2.df <- resid_mod2$residual

# Latex code for table
xtable(resid_mod2.df)

# Signifikanter Differenzentest *yay*
anova(surveyfit_mod1, surveyfit_mod2)

```

